# Generated by Django 5.1.6 on 2025-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Butterfly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='butterflies/')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('characteristics', models.TextField()),
            ],
        ),
    ]
