# Generated by Django 5.1.6 on 2025-03-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ButterflyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butterfly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='butterflies/media/'),
        ),
        migrations.AlterField(
            model_name='butterfly',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='butterflies/media/'),
        ),
    ]
