# Generated by Django 5.1.6 on 2025-03-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ButterflyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterfly',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butterflies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='butterflymedia',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butterfly_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
