# Generated by Django 5.1.6 on 2025-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ButterflyApp', '0002_alter_butterfly_image_alter_butterfly_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterflymedia',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
